INSERT INTO APP.PART (PART_ID, PART_NAME, PART_PRICE, PART_FORM_FACTOR) VALUES (1, 'NVIDIA GeForce 900', 199.99, 'Desktop');
INSERT INTO APP.PART (PART_ID, PART_NAME, PART_PRICE, PART_FORM_FACTOR) VALUES (2, 'LG Pixel Perfect', 149.99, 'Independent');
INSERT INTO APP.PART (PART_ID, PART_NAME, PART_PRICE, PART_FORM_FACTOR) VALUES (3, 'Seagate SSD ', 60.99, 'Desktop');
INSERT INTO APP.PART (PART_ID, PART_NAME, PART_PRICE, PART_FORM_FACTOR) VALUES (4, 'Samsung SSD', 80.99, 'Laptop');
INSERT INTO APP.PART (PART_ID, PART_NAME, PART_PRICE, PART_FORM_FACTOR) VALUES (5, 'GeoTex Motherboard', 50.99, 'Desktop');
INSERT INTO APP.PART (PART_ID, PART_NAME, PART_PRICE, PART_FORM_FACTOR) VALUES (6, 'Logitech Keyboard', 20.99, 'Independent');