INSERT INTO APP.LINE (LINE_ID, ORDER_ID, PART_ID, LINE_QTY) VALUES (1, 1, 1, 1);
INSERT INTO APP.LINE (LINE_ID, ORDER_ID, PART_ID, LINE_QTY) VALUES (2, 1, 2, 2);
INSERT INTO APP.LINE (LINE_ID, ORDER_ID, PART_ID, LINE_QTY) VALUES (3, 1, 3, 1);