INSERT INTO APP.PRESET (PRESET_ID, PRESET_NAME) VALUES (4, 'Lenovo');
INSERT INTO APP.PRESET (PRESET_ID, PRESET_NAME) VALUES (5, 'Dell Gaming PC');
INSERT INTO APP.PRESET (PRESET_ID, PRESET_NAME) VALUES (6, 'Dell Desktop Gaming PC');
INSERT INTO APP.PRESET (PRESET_ID, PRESET_NAME) VALUES (7, 'HP Workstation');