INSERT INTO APP.PRESET_PART (PRESET_ID, PART_ID) VALUES (4, 1);
INSERT INTO APP.PRESET_PART (PRESET_ID, PART_ID) VALUES (4, 2);
INSERT INTO APP.PRESET_PART (PRESET_ID, PART_ID) VALUES (4, 3);
INSERT INTO APP.PRESET_PART (PRESET_ID, PART_ID) VALUES (4, 4);