INSERT INTO APP.LINE (ORDER_ID, PART_ID, LINE_QTY) VALUES (1, 1, 1);
INSERT INTO APP.LINE (ORDER_ID, PART_ID, LINE_QTY) VALUES (1, 3, 2);
INSERT INTO APP.LINE (ORDER_ID, PART_ID, LINE_QTY) VALUES (1, 4, 1);