INSERT INTO APP.PART_ATTRIBUTE (PART_ID, PART_ATTRIBUTE_TYPE, PART_ATTRIBUTE_VALUE) VALUES (1, 'DDR5 GB', '1');
INSERT INTO APP.PART_ATTRIBUTE (PART_ID, PART_ATTRIBUTE_TYPE, PART_ATTRIBUTE_VALUE) VALUES (1, 'MHZ', '4.7');
INSERT INTO APP.PART_ATTRIBUTE (PART_ID, PART_ATTRIBUTE_TYPE, PART_ATTRIBUTE_VALUE) VALUES (2, 'RANDOMNESS', '5');
INSERT INTO APP.PART_ATTRIBUTE (PART_ID, PART_ATTRIBUTE_TYPE, PART_ATTRIBUTE_VALUE) VALUES (1, 'TYPE', 'Graphics Card');
INSERT INTO APP.PART_ATTRIBUTE (PART_ID, PART_ATTRIBUTE_TYPE, PART_ATTRIBUTE_VALUE) VALUES (2, 'TYPE', 'Monitor');
INSERT INTO APP.PART_ATTRIBUTE (PART_ID, PART_ATTRIBUTE_TYPE, PART_ATTRIBUTE_VALUE) VALUES (3, 'TYPE', 'Storage');
INSERT INTO APP.PART_ATTRIBUTE (PART_ID, PART_ATTRIBUTE_TYPE, PART_ATTRIBUTE_VALUE) VALUES (4, 'TYPE', 'Storage');
INSERT INTO APP.PART_ATTRIBUTE (PART_ID, PART_ATTRIBUTE_TYPE, PART_ATTRIBUTE_VALUE) VALUES (5, 'TYPE', 'Motherboard');
INSERT INTO APP.PART_ATTRIBUTE (PART_ID, PART_ATTRIBUTE_TYPE, PART_ATTRIBUTE_VALUE) VALUES (6, 'TYPE', 'Keyboard');